### ISSUE TITLE
Protected `navigator.platform` and `navigator.vendor`

### ISSUE THREAD

**Issue by evilebottnawi** [tarampampam/random-user-agent#7]
## Steps to reproduce:
1. Change on random user-agent with platform other than the current (if you on linux, change on window)
2. Go to http://browserspy.dk/browser.php
3. See `navigator.platform` and `navigator.vendor`
## Expected behaviour:

Fake value, not real.
## Actual behaviour:

Real value

---
### System information:

**Browser version**:

```
Google Chrome "53.0.2785.116 (64-bit), stable channel
```

**Extension version**:
latest

**Comment by tarampampam** [comment]
Thx 4 your report!

This is good idea! Maybe some time later I will add this feature, not right now.

**Comment by eternal-sorrow** [comment]
double this

**Comment by neroux** [comment]
Implemented as of 4acd710

**Comment by weranda** [comment]
Hi. Open internet.yandex.ru and you get the true appVersion & userAgent. Do you can to fix it?

**Comment by neroux** [comment]
@weranda Thats a different issue than the one reported here and addressed by #24. #25 should fix it

**Comment by tarampampam** [comment]
@weranda Open extension settings, enable "JavaScript prodection" (disabled dy default) and check again, please.

**Comment by weranda** [comment]
@tarampampam 
Still doesn't work. I enable "JS protection" (in russian — "Скрывать настоящий User-Agent...") and do nothing happend.
Look this: https://drive.google.com/file/d/0B9SxmkmKaeHaa213bjN5QUFIM2M/view

**Comment by neroux** [comment]
@weranda Please continue in #24 as this issue here is unrelated and #24 is most likely applicable.
